### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by loicnico96** [loicnico96/roborally#9]
Bugs:
- [ ] Implement conveyor belt collisions
- [ ] Implement virtual mode

Interface:
- [ ] Hide player hand outside of Program phase
- [ ] Improve background design
- [ ] Improve player card design
- [ ] Improve buttons
- [ ] Complete tooltips
- [ ] Add animation on damage
- [ ] Add animation on destruction

Features:
- [ ] Implement Water
- [ ] Add "Flood Zone" board
- [ ] Add board checkpoints
- [ ] Add "Exchange" board
- [ ] Add "Cross" board
- [ ] Add board features
- [ ] Implement Teleporters
- [ ] Add "Chasm" board
- [ ] Implement Randomizers
- [ ] Add "Gear Box" board
- [ ] Implement Pushers
- [ ] Add "Pit Maze" board
- [ ] Implement Flamethrowers
- [ ] Add "Blast Furnace" board
- [ ] Implement Portals
- [ ] Implement Oil
- [ ] Add "Machine Shop" board
- [ ] Implement Ledges
- [ ] Add "Coliseum" board

Rooms:
- [ ] Add ability to create room
- [ ] Add ability to start game
- [ ] Add ability to enter / leave room
- [ ] Add lookup for rooms
- [ ] Add "rooms" route
